on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start Redis
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: 3.2.1

      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop
      - name: Set up MySql8.0
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: 8.0
          mysql database: fanatic
          mysql root password: 123456789

      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.14
        id: go

      - uses: actions/checkout@v2

      - name: download and Test
        run: |
          go mod download
          go build fanatic
          go test fanatic/test
