on:
  push:
    branches:
      - master
jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop
      - name: Set up MySql8.0
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: 8.0
          mysql database: fanatic
          mysql root password: 123456789

      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.14
        id: go

      - uses: actions/checkout@v2

      - name: download
        run: go mod download

      - name: Build
        run: |
          go build fanatic
          ./fanatic

      - name: Test
        run: go test fanatic/test
